# Generated by Django 4.0.4 on 2022-07-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_rename_brand_merch_rename_brand_product_merch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merch',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='merch',
            new_name='brand',
        ),
    ]
